version: '2'
services:
  mvncont:
    image: amk/maven
    container_name: repos-maven
    environment:
      - SITE_DIR_NAME=repos
    volumes:
      - ./reposdata:/repos
    ports:
      - 8000:8000
    tty: true
    networks:
      - reposnet
    mem_limit: 1024M

networks:
  reposnet:
    driver: bridge
